replicaCount: 1
updateStrategy: {}
  # When a StatefulSet's .spec.updateStrategy.type is set to OnDelete, 
  # the StatefulSet controller will not automatically update the Pods
  # in a StatefulSet. Users must manually delete Pods to cause the
  # controller to create new Pods that reflect modifications made
  # to a StatefulSet's .spec.template.
  # 
  # type: OnDelete
  # 
  # or
  # 
  # When a StatefulSet's .spec.updateStrategy.type is set to RollingUpdate,
  # the StatefulSet controller will delete and recreate each Pod in the StatefulSet.
  # It will proceed in the same order as Pod termination (from the largest ordinal 
  # to the smallest), updating each Pod one at a time. It will wait until an updated
  # Pod is Running and Ready prior to updating its predecessor.
  # 
  # type: RollingUpdate
  # rollingUpdate:
  #   partition: 1
image:
  repository: osixia/openldap
  tag: 1.5.0
  pullPolicy: Always
  # pullSecret: harbor

# Set the container log level
# Valid log levels: none, error, warning, info (default), debug, trace
logLevel: debug

# Spcifies an existing secret to be used for admin and config user passwords
existingSecret: ""
# settings for enabling TLS with custom certificate
customTLS:
  enabled: false
  secret: ""  # The name of a kubernetes.io/tls type secret to use for TLS
  CA:
    enabled: false
## Add additional labels to all resources
extraLabels: {}
## Add additional annotations to pods
podAnnotations: {}
service:
  annotations: {}

  ldapPort: 389
  sslLdapPort: 636

  ## If service type NodePort, define the value here
  #ldapPortNodePort:
  #sslLdapPortNodePort:
  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  #loadBalancerIP: 
  #loadBalancerSourceRanges: []
  type: ClusterIP

# Default configuration for openldap as environment variables. These get injected directly in the container.
# Use the env variables from https://github.com/osixia/docker-openldap#beginner-guide
env:
 LDAP_LOG_LEVEL: "256"
 LDAP_ORGANISATION: "Wacker GmbH"
 LDAP_DOMAIN: "wacker.com"
 LDAP_READONLY_USER: "false"
 LDAP_READONLY_USER_USERNAME: "readonly"
 LDAP_READONLY_USER_PASSWORD: "readonly"
 LDAP_RFC2307BIS_SCHEMA: "false"
 LDAP_BACKEND: "mdb"
 LDAP_TLS: "true"
 LDAP_TLS_CRT_FILENAME: "tls.crt"
 LDAP_TLS_KEY_FILENAME: "tls.key"
 LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
 LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
 LDAP_TLS_ENFORCE: "false"
 CONTAINER_LOG_LEVEL: "4"
 LDAP_TLS_REQCERT: "never"
 KEEP_EXISTING_CONFIG: "false"
 LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
 LDAP_SSL_HELPER_PREFIX: "ldap"
 LDAP_TLS_VERIFY_CLIENT: "never"
 LDAP_TLS_PROTOCOL_MIN: "3.0"
 LDAP_TLS_CIPHER_SUITE: "NORMAL"

replication:
  enabled: false    
  # Enter the name of your cluster, defaults to "cluster.local"
  clusterName: "cluster.local"
  retry: 60
  timeout: 1
  interval: 00:00:00:10
  starttls: "critical"
  tls_reqcert: "never"
## Persist data to a persistent volume
persistence:
  enabled: true
  storageClass: "kubermatic-fast"
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources:
 requests:
   cpu: "100m"
   memory: "256Mi"
 limits:
   cpu: "500m"
   memory: "512Mi"

nodeSelector: {}

tolerations: []


## test container details
test:
  enabled: false
  image:
    repository: dduportal/bats
    tag: 0.4.0
